[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/entries"
  to = "/.netlify/functions/entries"
  status = 200
  force = true

[[redirects]]
  from = "/entries/today"
  to = "/.netlify/functions/entries-today"
  status = 200
  force = true

[[redirects]]
  from = "/entries/reset"
  to = "/.netlify/functions/entries-reset"
  status = 200
  force = true

[[redirects]]
  from = "/entries.csv"
  to = "/.netlify/functions/entries-csv"
  status = 200
  force = true

[[redirects]]
  from = "/screen-time"
  to = "/.netlify/functions/screen-time"
  status = 200
  force = true

[[redirects]]
  from = "/screen-time/today"
  to = "/.netlify/functions/screen-time-today"
  status = 200
  force = true

[[redirects]]
  from = "/notes/shorten"
  to = "/.netlify/functions/note-shorten"
  status = 200
  force = true
